common: &common
  server_url: 'https://sso.university.innopolis.ru'
  authorize_url: '/adfs/oauth2/authorize'
  token_url: '/adfs/oauth2/token'
  info_url: '/adfs/oauth2/tokeninfo'

dev:
  <<: *common
  client_id: 7d0eb0b9-ad73-4942-be55-284facc99a95
  client_secret: HWLR_BUBEbCXocfItLaQN3Jm84kxVDEVy0wWVMU4

production:
  <<: *common
  client_id: {{{env.INNOPOLIS_SSO_CLIENT_ID}}}
  client_secret: {{{env.INNOPOLIS_SSO_CLIENT_SECRET}}}
